import 'package:tekflat_design/tekflat_design.dart';
import 'package:tekflat_design_docs/runner/runner.dart';
import 'package:tekflat_design_docs/src/app/app.dart';
import 'package:tekflat_design_docs/src/core/core.dart';
import 'package:flutter/material.dart';

class DialogsAPIsWidget extends StatelessWidget {
  const DialogsAPIsWidget({super.key});

  List<APITableModel> _getDataSourceOptionDialogs() => [
        APITableModel(
          id: 1,
          property: 'context',
          description: S.current.optionDialogsAPIDescription1,
          type: 'BuildContext',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 2,
          property: 'type',
          description: S.current.optionDialogsAPIDescription2,
          type: 'TekDialogType',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 3,
          property: 'onClickButtonRight',
          description: S.current.optionDialogsAPIDescription3,
          type: '',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 4,
          property: 'onClickButtonLeft',
          description: S.current.optionDialogsAPIDescription4,
          type: 'VoidCallback',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 5,
          property: 'title',
          description: S.current.optionDialogsAPIDescription5,
          type: 'String',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 6,
          property: 'customTitle',
          description: S.current.optionDialogsAPIDescription6,
          type: 'Widget',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 7,
          property: 'content',
          description: S.current.optionDialogsAPIDescription7,
          type: 'String',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 8,
          property: 'buttonCancel',
          description: S.current.optionDialogsAPIDescription8,
          type: 'String',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 9,
          property: 'buttonText',
          description: S.current.optionDialogsAPIDescription9,
          type: 'String',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 10,
          property: 'customContent',
          description: S.current.optionDialogsAPIDescription10,
          type: 'Widget',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 11,
          property: 'width',
          description: S.current.optionDialogsAPIDescription11,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
      ];

  List<APITableModel> _getDataSourceCustomizeDialogs() => [
        APITableModel(
          id: 1,
          property: 'context',
          description: S.current.customizeDialogsAPIDescription1,
          type: 'BuildContext',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 2,
          property: 'width',
          description: S.current.customizeDialogsAPIDescription2,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 3,
          property: 'height',
          description: S.current.customizeDialogsAPIDescription3,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 4,
          property: 'barrierDismissible',
          description: S.current.customizeDialogsAPIDescription4,
          type: 'bool',
          defaultValue: 'true',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 5,
          property: 'color',
          description: S.current.customizeDialogsAPIDescription5,
          type: 'Color',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 6,
          property: 'shape',
          description: S.current.customizeDialogsAPIDescription6,
          type: 'BoxShape',
          defaultValue: 'BoxShape.rectangle',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 7,
          property: 'borderRadius',
          description: S.current.customizeDialogsAPIDescription7,
          type: 'BorderRadiusGeometry',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 8,
          property: 'padding',
          description: S.current.customizeDialogsAPIDescription8,
          type: 'EdgeInsets',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 9,
          property: 'title',
          description: S.current.customizeDialogsAPIDescription9,
          type: 'String',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 10,
          property: 'onPressedToTitle',
          description: S.current.customizeDialogsAPIDescription10,
          type: 'VoidCallback',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 11,
          property: 'customizeOkText',
          description: S.current.customizeDialogsAPIDescription11,
          type: 'String',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 12,
          property: 'customizeCancelText',
          description: S.current.customizeDialogsAPIDescription12,
          type: 'String',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 13,
          property: 'onOkPressed',
          description: S.current.customizeDialogsAPIDescription13,
          type: 'VoidCallback',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 14,
          property: 'onCancelPressed',
          description: S.current.customizeDialogsAPIDescription14,
          type: 'VoidCallback',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 15,
          property: 'content',
          description: S.current.customizeDialogsAPIDescription15,
          type: 'Widget',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 16,
          property: 'showFooter',
          description: S.current.customizeDialogsAPIDescription16,
          type: 'bool',
          defaultValue: 'true',
          version: AppMode().appMode.version,
        ),
      ];

  List<APITableModel> _getDataSourceDefaultDialogs() => [
        APITableModel(
          id: 1,
          property: 'context',
          description: S.current.defaultDialogsAPIDescription1,
          type: 'BuildContext',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 2,
          property: 'width',
          description: S.current.defaultDialogsAPIDescription2,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 3,
          property: 'height',
          description: S.current.defaultDialogsAPIDescription3,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 4,
          property: 'barrierDismissible',
          description: S.current.defaultDialogsAPIDescription4,
          type: 'bool',
          defaultValue: 'true',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 5,
          property: 'color',
          description: S.current.defaultDialogsAPIDescription5,
          type: 'Color',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 6,
          property: 'shape',
          description: S.current.defaultDialogsAPIDescription6,
          type: 'BoxShape',
          defaultValue: 'BoxShape.rectangle',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 7,
          property: 'borderRadius',
          description: S.current.defaultDialogsAPIDescription7,
          type: 'BorderRadiusGeometry',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 8,
          property: 'content',
          description: S.current.defaultDialogsAPIDescription8,
          type: 'Widget',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
      ];

  @override
  Widget build(BuildContext context) => Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          TekVSpace.p4,
          const DocsTitleItemWidget(title: 'Option Dialogs'),
          TekVSpace.p8,
          APITableWidget(
            widthOfPropertyColumn: 170,
            dataSources: _getDataSourceOptionDialogs(),
          ),
          TekVSpace.p18,
          const DocsTitleItemWidget(title: 'Customize Dialogs'),
          TekVSpace.p8,
          APITableWidget(
            widthOfPropertyColumn: 170,
            dataSources: _getDataSourceCustomizeDialogs(),
          ),
          TekVSpace.p18,
          const DocsTitleItemWidget(title: 'Default Dialogs'),
          TekVSpace.p8,
          APITableWidget(
            widthOfPropertyColumn: 170,
            dataSources: _getDataSourceDefaultDialogs(),
          ),
        ],
      );
}
