import 'package:tekflat_design/tekflat_design.dart';
import 'package:tekflat_design_docs/runner/runner.dart';
import 'package:tekflat_design_docs/src/app/app.dart';
import 'package:tekflat_design_docs/src/core/core.dart';
import 'package:flutter/material.dart';

class ButtonsAPIsWidget extends StatelessWidget {
  const ButtonsAPIsWidget({Key? key}) : super(key: key);

  List<APITableModel> _getDataSourceDefaultButton() => [
        APITableModel(
          id: 2,
          property: 'size',
          description: S.current.buttonAPIDescription2,
          type: 'TekButtonSize',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 3,
          property: 'type',
          description: S.current.buttonAPIDescription3,
          type: 'TekButtonType',
          defaultValue: 'TekButtonType.none',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 4,
          property: 'onPressed',
          description: S.current.buttonAPIDescription4,
          type: 'VoidCallback',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 5,
          property: 'disabled',
          description: S.current.buttonAPIDescription5,
          type: 'bool',
          defaultValue: 'false',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 6,
          property: 'loading',
          description: S.current.buttonAPIDescription6,
          type: 'bool',
          defaultValue: 'false',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 7,
          property: 'text',
          description: S.current.buttonAPIDescription7,
          type: 'String',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 8,
          property: 'child',
          description: S.current.buttonAPIDescription8,
          type: 'Widget',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 9,
          property: 'width',
          description: S.current.buttonAPIDescription9,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 10,
          property: 'height',
          description: S.current.buttonAPIDescription10,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 11,
          property: 'padding',
          description: S.current.buttonAPIDescription11,
          type: 'EdgeInsets',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 12,
          property: 'background',
          description: S.current.buttonAPIDescription12,
          type: 'Color',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 13,
          property: 'hoverColor',
          description: S.current.buttonAPIDescription13,
          type: 'Color',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 14,
          property: 'shadowColor',
          description: S.current.buttonAPIDescription14,
          type: 'Color',
          defaultValue: 'Colors.transparent',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 15,
          property: 'elevation',
          description: S.current.buttonAPIDescription15,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 16,
          property: 'splashFactory',
          description: S.current.buttonAPIDescription16,
          type: 'InteractiveInkFeatureFactory',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 17,
          property: 'boxShadow',
          description: S.current.buttonAPIDescription17,
          type: 'List<BoxShadow>',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 18,
          property: 'shape',
          description: S.current.buttonAPIDescription18,
          type: 'OutlinedBorder',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 19,
          property: 'textColor',
          description: S.current.buttonAPIDescription19,
          type: 'Color',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 20,
          property: 'fontSize',
          description: S.current.buttonAPIDescription20,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 21,
          property: 'textStyle',
          description: S.current.buttonAPIDescription21,
          type: 'TextStyle',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 22,
          property: 'textAlign',
          description: S.current.buttonAPIDescription22,
          type: 'TextAlign',
          defaultValue: ' TextAlign.center',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 23,
          property: 'maxLines',
          description: S.current.buttonAPIDescription23,
          type: 'int',
          defaultValue: '4',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 24,
          property: 'alignment',
          description: S.current.buttonAPIDescription24,
          type: 'AlignmentGeometry',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
      ];

  List<APITableModel> _getDataSourceButtonIcon() => [
        APITableModel(
          id: 1,
          property: 'iconData',
          description: S.current.buttonIconAPIDescription1,
          type: 'IconData',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 2,
          property: 'icon',
          description: S.current.buttonIconAPIDescription2,
          type: 'Icon',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 3,
          property: 'spaceBetweenIconAndText',
          description: S.current.buttonIconAPIDescription3,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 4,
          property: 'mainAxisSize',
          description: S.current.buttonIconAPIDescription4,
          type: 'MainAxisSize',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 5,
          property: 'mainAxisAlignment',
          description: S.current.buttonIconAPIDescription5,
          type: 'MainAxisAlignment',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 6,
          property: 'iconBeforeText',
          description: S.current.buttonIconAPIDescription6,
          type: 'bool',
          defaultValue: 'true',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 7,
          property: 'iconIsInEdge',
          description: S.current.buttonIconAPIDescription7,
          type: 'bool',
          defaultValue: 'false',
          version: AppMode().appMode.version,
        ),
      ];

  List<APITableModel> _getDataSourceInkwellButton() => [
        APITableModel(
          id: 1,
          property: 'text',
          description: S.current.inkwellButtonAPIDescription1,
          type: 'String',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 2,
          property: 'child',
          description: S.current.inkwellButtonAPIDescription2,
          type: 'Widget',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 3,
          property: 'onPressed',
          description: S.current.inkwellButtonAPIDescription3,
          type: 'VoidCallback',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 4,
          property: 'textColor',
          description: S.current.inkwellButtonAPIDescription4,
          type: 'Color',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 5,
          property: 'textFontSize',
          description: S.current.inkwellButtonAPIDescription5,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 6,
          property: 'textFontWeight',
          description: S.current.inkwellButtonAPIDescription6,
          type: 'FontWeight',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
      ];

  List<APITableModel> _getDataSourceTextButton() => [
        APITableModel(
          id: 1,
          property: 'text',
          description: S.current.buttonGesAPIDescription1,
          type: 'String',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 2,
          property: 'child',
          description: S.current.buttonGesAPIDescription2,
          type: 'Widget',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 3,
          property: 'onPressed',
          description: S.current.buttonGesAPIDescription3,
          type: 'VoidCallback',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 4,
          property: 'textColor',
          description: S.current.buttonGesAPIDescription4,
          type: 'Color',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 5,
          property: 'textFontSize',
          description: S.current.buttonGesAPIDescription5,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 6,
          property: 'textFontWeight',
          description: S.current.buttonGesAPIDescription6,
          type: 'FontWeight',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 7,
          property: 'cursor',
          description: S.current.buttonGesAPIDescription7,
          type: 'MouseCursor',
          defaultValue: 'SystemMouseCursors.click',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 8,
          property: 'type',
          description: S.current.buttonGesAPIDescription8,
          type: 'TekButtonGDType',
          defaultValue: 'required',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 9,
          property: 'iconData',
          description: S.current.buttonGesAPIDescription9,
          type: 'IconData',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 10,
          property: 'size',
          description: S.current.buttonGesAPIDescription10,
          type: 'double',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 11,
          property: 'color',
          description: S.current.buttonGesAPIDescription11,
          type: 'Color',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 12,
          property: 'icon',
          description: S.current.buttonGesAPIDescription12,
          type: 'Widget',
          defaultValue: 'null',
          version: AppMode().appMode.version,
        ),
      ];

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        TekVSpace.p4,
        const DocsTitleItemWidget(title: 'Default Button'),
        TekVSpace.p8,
        APITableWidget(
          dataSources: _getDataSourceDefaultButton(),
        ),
        TekVSpace.p18,
        DocsTitleItemWidget(title: 'Button Icon (${S.current.extendedFormTekButton})'),
        TekVSpace.p8,
        APITableWidget(
          widthOfPropertyColumn: 220,
          dataSources: _getDataSourceButtonIcon(),
        ),
        TekVSpace.p18,
        const DocsTitleItemWidget(title: 'Button Inkwell'),
        TekVSpace.p8,
        APITableWidget(
          widthOfPropertyColumn: 180,
          dataSources: _getDataSourceInkwellButton(),
        ),
        TekVSpace.p18,
        const DocsTitleItemWidget(title: 'Button Gesture Detector'),
        TekVSpace.p8,
        APITableWidget(
          widthOfTypeColumn: 260,
          widthOfPropertyColumn: 180,
          dataSources: _getDataSourceTextButton(),
        ),
      ],
    );
  }
}
