import 'package:flutter/material.dart';
import 'package:tekflat_design/tekflat_design.dart';
import 'package:tekflat_design_docs/runner/runner.dart';
import 'package:tekflat_design_docs/src/app/app.dart';
import 'package:tekflat_design_docs/src/core/core.dart';

class ButtonsAPIsWidget extends StatelessWidget {
  const ButtonsAPIsWidget({Key? key}) : super(key: key);

  List<APITableModel> _getDataSourceTekButton() => [
        APITableModel(
          id: 1,
          property: 'size',
          description: S.current.buttonAPIDescriptionSize,
          type: 'TekButtonSize',
          defaultValue: 'TekButtonSize.medium',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 2,
          property: 'type',
          description: S.current.buttonAPIDescriptionType,
          type: 'TekButtonType',
          defaultValue: 'TekButtonType.none',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 3,
          property: 'onPressed',
          description: S.current.buttonAPIDescriptionOnPressed,
          type: 'VoidCallback',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 4,
          property: 'onHover',
          description: S.current.buttonAPIDescriptionOnHover,
          type: 'Function(bool?)?',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 5,
          property: 'disabled',
          description: S.current.buttonAPIDescriptionDisabled,
          type: 'bool',
          defaultValue: 'false',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 6,
          property: 'loading',
          description: S.current.buttonAPIDescriptionDisabled,
          type: 'bool',
          defaultValue: 'false',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 7,
          property: 'text',
          description: S.current.buttonAPIDescriptionText,
          type: 'String',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 8,
          property: 'child',
          description: S.current.buttonAPIDescriptionChild,
          type: 'Widget',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 9,
          property: 'icon',
          description: S.current.buttonAPIDescriptionIcon,
          type: 'Widget',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 10,
          property: 'iconData',
          description: S.current.buttonAPIDescriptionIconData,
          type: 'IconData',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 11,
          property: 'iconIsRight',
          description: S.current.buttonAPIDescriptionIconIsRight,
          type: 'bool',
          defaultValue: 'false',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 12,
          property: 'width',
          description: S.current.buttonAPIDescriptionWidth,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 13,
          property: 'height',
          description: S.current.buttonAPIDescriptionHeight,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 14,
          property: 'padding',
          description: S.current.buttonAPIDescriptionPadding,
          type: 'EdgeInsets',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 15,
          property: 'background',
          description: S.current.buttonAPIDescriptionBackground,
          type: 'Color',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 16,
          property: 'hoverColor',
          description: S.current.buttonAPIDescriptionHoverColor,
          type: 'Color',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 17,
          property: 'shadowColor',
          description: S.current.buttonAPIDescriptionShadowColor,
          type: 'Color',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 18,
          property: 'elevation',
          description: S.current.buttonAPIDescriptionElevation,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 19,
          property: 'splashFactory',
          description: S.current.buttonAPIDescriptionSplashFactory,
          type: 'InteractiveInkFeatureFactory',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 20,
          property: 'boxShadow',
          description: S.current.buttonAPIDescriptionBoxShadow,
          type: 'List<BoxShadow>',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 21,
          property: 'shape',
          description: S.current.buttonAPIDescriptionShape,
          type: 'OutlinedBorder',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 22,
          property: 'textColor',
          description: S.current.buttonAPIDescriptionTextColor,
          type: 'Color',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 23,
          property: 'fontSize',
          description: S.current.buttonAPIDescriptionFontSize,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 24,
          property: 'textStyle',
          description: S.current.buttonAPIDescriptionTextStyle,
          type: 'TextStyle',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 25,
          property: 'textAlign',
          description: S.current.buttonAPIDescriptionTextAlign,
          type: 'TextAlign',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 26,
          property: 'maxLines',
          description: S.current.buttonAPIDescriptionMaxLines,
          type: 'int',
          defaultValue: '1',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 27,
          property: 'alignment',
          description: S.current.buttonAPIDescriptionAlignment,
          type: 'Alignment',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 28,
          property: 'iconSize',
          description: S.current.buttonAPIDescriptionIconSize,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 29,
          property: 'iconColor',
          description: S.current.buttonAPIDescriptionIconColor,
          type: 'Color',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 30,
          property: 'mainAxisAlignment',
          description: S.current.buttonAPIDescriptionMainAxisAlignment,
          type: 'MainAxisAlignment',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 31,
          property: 'spaceBetweenIconAndText',
          description: S.current.buttonAPIDescriptionSpaceBetweenIconAndText,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 32,
          property: 'fontWeight',
          description: S.current.buttonAPIDescriptionFontWeight,
          type: 'FontWeight',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 33,
          property: 'mainAxisSize',
          description: S.current.buttonAPIDescriptionMainAxisSize,
          type: 'MainAxisSize',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 34,
          property: 'borderColor',
          description: S.current.buttonAPIDescriptionBorderColor,
          type: 'Color',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 35,
          property: 'borderWidth',
          description: S.current.buttonAPIDescriptionBorderWidth,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 36,
          property: 'borderRadius',
          description: S.current.buttonAPIDescriptionBorderRadius,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
      ];

  List<APITableModel> _getDataSourceTekLink() => [
        APITableModel(
          id: 1,
          property: 'size',
          description: S.current.linkAPIDescriptionSize,
          type: 'TekLinkSize',
          defaultValue: 'TekLinkSize.small',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 2,
          property: 'type',
          description: S.current.linkAPIDescriptionType,
          type: 'TekLinkType',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 3,
          property: 'text',
          description: S.current.linkAPIDescriptionText,
          type: 'String',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 4,
          property: 'iconData',
          description: S.current.linkAPIDescriptionIconData,
          type: 'IconData',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 5,
          property: 'icon',
          description: S.current.linkAPIDescriptionIcon,
          type: 'Widget',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 6,
          property: 'child',
          description: S.current.linkAPIDescriptionChild,
          type: 'Widget',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 7,
          property: 'onPressed',
          description: S.current.linkAPIDescriptionOnPressed,
          type: 'VoidCallback',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 8,
          property: 'cursor',
          description: S.current.linkAPIDescriptionCursor,
          type: 'MouseCursor',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 9,
          property: 'disabled',
          description: S.current.linkAPIDescriptionDisabled,
          type: 'bool',
          defaultValue: 'false',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 10,
          property: 'iconSize',
          description: S.current.linkAPIDescriptionIconSize,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 11,
          property: 'iconColor',
          description: S.current.linkAPIDescriptionIconColor,
          type: 'Color',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 12,
          property: 'textStyle',
          description: S.current.linkAPIDescriptionTextStyle,
          type: 'TextStyle',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 13,
          property: 'maxLines',
          description: S.current.linkAPIDescriptionMaxLines,
          type: 'int',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 14,
          property: 'textColor',
          description: S.current.linkAPIDescriptionTextColor,
          type: 'Color',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 15,
          property: 'textSize',
          description: S.current.linkAPIDescriptionTextSize,
          type: 'double',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 16,
          property: 'iconIsRight',
          description: S.current.linkAPIDescriptionIconIsRight,
          type: 'bool',
          defaultValue: 'false',
          version: AppMode().appMode.version,
        ),
        APITableModel(
          id: 17,
          property: 'fontWeight',
          description: S.current.linkAPIDescriptionFontWeight,
          type: 'FontWeight',
          defaultValue: '_',
          version: AppMode().appMode.version,
        ),
      ];

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        TekVSpace.p4,
        const DocsTitleItemWidget(title: 'Tek Button'),
        TekVSpace.p8,
        APITableWidget(dataSources: _getDataSourceTekButton()),
        TekVSpace.p18,
        const DocsTitleItemWidget(title: 'Tek Link'),
        TekVSpace.p8,
        APITableWidget(dataSources: _getDataSourceTekLink()),
      ],
    );
  }
}
